INSERT INTO TEAM (id, NAME, LOCATION, FOUNDED_DATE) VALUES (1, 'THE_FIRST', 'KOREA', '20230101');
INSERT INTO TEAM (id, NAME, LOCATION, FOUNDED_DATE) VALUES (2, 'THE_SECOND', 'KOREA', '20230102');
INSERT INTO TEAM (id, NAME, LOCATION, FOUNDED_DATE) VALUES (3, 'THE_THIRD', 'USA', '20230103');
INSERT INTO TEAM (id, NAME, LOCATION, FOUNDED_DATE) VALUES (4, 'THE_LAST', 'JAPAN', '20230104');

INSERT INTO MEMBER (id, FIRST_NAME, LAST_NAME, ADDRESS, JOINED_DATE, TEAM_ID) VALUES (1, 'ONE', 'KIM', 'SEOUL', '20230101', 1);
INSERT INTO MEMBER (id, FIRST_NAME, LAST_NAME, ADDRESS, JOINED_DATE, TEAM_ID) VALUES (2, 'TWO', 'LEE', 'TOKYO', '20230102', 4);
INSERT INTO MEMBER (id, FIRST_NAME, LAST_NAME, ADDRESS, JOINED_DATE, TEAM_ID) VALUES (3, 'THREE', 'PARK', 'DC', '20230103', 3);
INSERT INTO MEMBER (id, FIRST_NAME, LAST_NAME, ADDRESS, JOINED_DATE, TEAM_ID) VALUES (4, 'FOUR', 'NAM', 'SEOUL', '20230104', 1);
INSERT INTO MEMBER (id, FIRST_NAME, LAST_NAME, ADDRESS, JOINED_DATE, TEAM_ID) VALUES (5, 'FIVE', 'KANG', 'SEOUL', '20230105', 1);
INSERT INTO MEMBER (id, FIRST_NAME, LAST_NAME, ADDRESS, JOINED_DATE, TEAM_ID) VALUES (6, 'SIX', 'HONG', 'NEWYORK', '20230106', 3);
INSERT INTO MEMBER (id, FIRST_NAME, LAST_NAME, ADDRESS, JOINED_DATE, TEAM_ID) VALUES (7, 'SEVEN', 'HAN', 'OSAKA', '20230107', 4);
INSERT INTO MEMBER (id, FIRST_NAME, LAST_NAME, ADDRESS, JOINED_DATE, TEAM_ID) VALUES (8, 'EIGHT', 'YUN', 'UNKNOWN', '20230108', 1);
INSERT INTO MEMBER (id, FIRST_NAME, LAST_NAME, ADDRESS, JOINED_DATE, TEAM_ID) VALUES (9, 'NINE', 'LEE', 'UNKNOWN', '20230109', 1);
